services:
  - type: web
    name: tripsync-backend
    env: node
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
